sudo: required # force to run in container
env: # required for node_bcrypt
  - CXX=g++-4.8
os:
- linux
# - osx
# osx_image: xcode7.3
language: node_js
node_js:
- '6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - echo 'America/New_York' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - openssl aes-256-cbc -K $encrypted_e447456204f1_key -iv $encrypted_e447456204f1_iv
    -in .travis/id_rsa_travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - chmod +x $TRAVIS_BUILD_DIR/.travis/run_on_pull_requests
  - mv -fv .travis/ssh-config ~/.ssh/config
  - npm install -g coveralls
script:
  - yarn
  - yarn test -- -w="2"
  - 'if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then yarn coverage; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./.travis/run_on_pull_requests; fi'
